---
# Defaults
patroni_defaults_release_postgresql: '16.2'
patroni_defaults_release_patroni: '3.2.2'
patroni_defaults_release_consul: '1.18.1-1'

# Overridable values
_patroni_nolog: "{{ patroni_nolog | default(True) }}"

_patroni_cluster_hostgroup: "{{ patroni_cluster_group | default('patroni_cluster') }}"
_patroni_barman_hostgroup: "{{ patroni_barman_group | default('patroni_barman') }}"
_patroni_update_skip_hostgroup: "{{ patroni_update_skip_group | default('patroni_update_skip') }}"
_patroni_haproxy_hostgroup: "{{ patroni_haproxy_group | default('patroni_haproxy') }}"

_patroni_release_postgresql: "{{ patroni_release_postgresql | default(patroni_defaults_release_postgresql) }}"
_patroni_release_patroni: "{{ patroni_release_postgresql | default(patroni_defaults_release_patroni) }}"

_patroni_config_overwrite: "{{ patroni_config_overwrite | default(True) | bool }}"
_patroni_config_hostnames: "{{ patroni_config_hostnames | default(True) | bool }}"
_patroni_config_encoding: "{{ postgresql_locale | split('.') | last | regex_replace('-', '') }}"
_patroni_config_locale: "{{ postgresql_locale }}"

_patroni_watchdog_enable: "{{ patroni_watchdog_enable | default(True) }}"
_patroni_watchdog_mode: "{{ _patroni_watchdog_enable | bool | ternary('automatic', 'off') }}"

_patroni_cluster_port_psql: 5432
_patroni_cluster_port_restapi: 8008
_patroni_cluster_nodes: "{{ groups[_patroni_cluster_hostgroup] }}"
_patroni_cluster_release: "{{ _patroni_release_postgresql | split('.') | first }}"
_patroni_cluster_service_name: "{{ patroni_cluster_service_name | default('patroni') }}"
_patroni_cluster_name: "{{ patroni_cluster_name }}"
_patroni_cluster_api_username: "{{ patroni_cluster_api_username | default('patroni') }}"
_patroni_cluster_api_password: "{{ patroni_cluster_api_password }}"
_patroni_cluster_postgres_password: "{{ patroni_cluster_postgres_password }}"
_patroni_cluster_maxlag_failover: "{{ patroni_custer_maxlag_failover | default('1048576') }}"
_patroni_cluster_maxlag_sync: "{{ patroni_custer_maxlag_sync | default('-1') }}"
_patroni_cluster_replication_username: "{{ patroni_cluster_replication_username | default('replicator') }}"
_patroni_cluster_replication_password: "{{ patroni_cluster_replication_password }}"
_patroni_cluster_barman_username: "{{ patroni_cluster_barman_username | default('barman') }}"
_patroni_cluster_barman_password: "{{ patroni_cluster_barman_password }}"
_patroni_cluster_rewind_username: "{{ patroni_cluster_rewind_username | default('rewind') }}"
_patroni_cluster_rewind_password: "{{ patroni_cluster_rewind_password }}"
_patroni_cluster_backup_path: "{{ patroni_cluster_backup_path | default('/backups/patroni') }}"
_patroni_cluster_config_path: "{{ patroni_cluster_config_path | default('/etc/patroni') }}"
_patroni_cluster_config_file: "{{ _patroni_cluster_config_path }}/{{ (ansible_os_family == 'Debian') | ternary('config', 'patroni') }}.yml"
_patroni_cluster_start_timeout: "{{ patroni_cluster_start_timeout | default('60') }}"
_patroni_cluster_hba_extra: "{{ patroni_cluster_hba | default([]) }}"
_patroni_cluster_roles: "{{ patroni_cluster_roles | default([]) }}"
_patroni_cluster_databases: "{{ patroni_cluster_databases | default([]) }}"
_patroni_cluster_slot_barman: barman
_patroni_cluster_hba_base:
  - type: local
    database: all
    user: all
    auth_method: peer
  - type: host
    database: all
    user: all
    address: "127.0.0.1/32"
    auth_method: md5
  - type: host
    database: all
    user: all
    address: "::1/128"
    auth_method: md5
  - type: host
    database: all
    user: postgres
    address: "0.0.0.0/0"
    auth_method: reject
  - type: host
    database: replication
    user: "{{ _patroni_cluster_replication_username }}"
    address: "127.0.0.1/32"
    auth_method: md5
  - type: host
    database: replication
    user: "{{ _patroni_cluster_replication_username }}"
    address: "::1/128"
    auth_method: md5
  - type: host
    database: replication
    user: "{{ _patroni_cluster_replication_username }}"
    address: "0.0.0.0/0"
    auth_method: md5
  - type: host
    database: rewind
    user: "{{ _patroni_cluster_rewind_username }}"
    address: "127.0.0.1/32"
    auth_method: md5
  - type: host
    database: rewind
    user: "{{ _patroni_cluster_rewind_username }}"
    address: "::1/128"
    auth_method: md5
  - type: host
    database: rewind
    user: "{{ _patroni_cluster_rewind_username }}"
    address: "0.0.0.0/0"
    auth_method: md5
  - type: host
    database: all
    user: "{{ _patroni_cluster_barman_username }}"
    address: "127.0.0.1/32"
    auth_method: md5
  - type: host
    database: all
    user: "{{ _patroni_cluster_barman_username }}"
    address: "::1/128"
    auth_method: md5
  - type: host
    database: all
    user: "{{ _patroni_cluster_barman_username }}"
    address: "0.0.0.0/0"
    auth_method: md5
  - type: host
    database: replication
    user: "{{ _patroni_cluster_barman_username }}"
    address: "127.0.0.1/32"
    auth_method: md5
  - type: host
    database: replication
    user: "{{ _patroni_cluster_barman_username }}"
    address: "::1/128"
    auth_method: md5
  - type: host
    database: replication
    user: "{{ _patroni_cluster_barman_username }}"
    address: "0.0.0.0/0"
    auth_method: md5
  - type: host
    database: all
    user: all
    address: "0.0.0.0/0"
    auth_method: md5

consul_group: "{{ patroni_consul_group | default('patroni_consul') }}:{{ _patroni_cluster_hostgroup }}"
consul_update_skip_group: "{{ _patroni_update_skip_hostgroup }}:{{ _patroni_cluster_hostgroup }}"
consul_release: "{{ patroni_release_consul | default(patroni_defaults_release_consul) }}"
consul_datacenter_name: "{{ patroni_consul_datacenter | default('patroni') }}"
consul_backup_retention: "{{ patroni_consul_backup_retention | default('1440') }}"
consul_backup_minutes: "{{ patroni_consul_backup_period | default('*/5') }}"
consul_backup_hours: "{{ patroni_consul_backup_period | default('*') }}"
consul_backup_days: "{{ patroni_consul_backup_period | default('*') }}"

_patroni_addrkeys: ['ansible_default_ipv4', 'address']
_patroni_hostkeys: ['name', 'address']

_patroni_haproxy_config_file: "/etc/haproxy/haproxy.cfg"
_patroni_haproxy_user: "haproxy"
_patroni_haproxy_group: "haproxy"
_patroni_haproxy_listen_addr: "{{ patroni_haproxy_listen_addr | default('*') }}"
_patroni_haproxy_maxconn: "{{ patroni_haproxy_maxconn | default(1000) }}"
_patroni_haproxy_addrattrs: "{{ _patroni_config_hostnames | ternary('ansible_fqdn', _patroni_addrkeys) }}"
_patroni_haproxy_hostaddrs: "{{ _patroni_cluster_nodes |
  map('extract', hostvars, _patroni_haproxy_addrattrs) }}"
_patroni_haproxy_hostattrs: "{{ _patroni_cluster_nodes | zip(_patroni_haproxy_hostaddrs) }}"
_patroni_haproxy_nodes: "{{ _patroni_haproxy_hostattrs |
  map('zip', _patroni_hostkeys) |
  map('map', 'reverse') |
  map('community.general.dict') }}"
_patroni_haproxy_port_psql_master_local: 5432
_patroni_haproxy_port_psql_slave_local: 5433
_patroni_haproxy_port_ssh_master_local: 2222

_patroni_barman_user: "{{ patroni_barman_user | default('barman') }}"
_patroni_barman_group: "{{ patroni_barman_user | default('barman') }}"
_patroni_barman_home: "/var/lib/barman"
_patroni_barman_cron_crontab: "{{ patroni_barman_cron_crontab | default('* * * * *') }}"
_patroni_barman_backup_crontab: "{{ patroni_barman_backup_crontab | default('0 0 * * *') }}"
_patroni_barman_backup_dir: "{{ patroni_barman_backup_dir | default(_patroni_barman_home) }}"
_patroni_barman_ssh_keypair: "{{ _patroni_barman_home }}/.ssh/id_rsa"
_patroni_barman_conf_file: "/etc/{{ (ansible_os_family == 'Redhat') | ternary('barman/', '') }}barman.conf"
_patroni_barman_conf_log_file: "/var/log/barman/barman.log"
_patroni_barman_conf_dir: "/etc/barman{{ (ansible_os_family == 'RedHat') | ternary('/conf', '') }}.d"
_patroni_barman_conf_log_level: "{{ patroni_barman_conf_log_level | default('WARNING') }}"
_patroni_barman_conf_compression: "{{ patroni_barman_conf_compression | default('gzip') }}"
_patroni_barman_conf_bwlimit: "{{ patroni_barman_conf_bwlimit | default(0) }}"
_patroni_barman_conf_include: "{{ patroni_barman_conf_include | default('') }}"
_patroni_barman_conf_cluster: "{{ patroni_barman_conf_cluster | default('') }}"

# Hardcoded values
_patroni_groups_master: "_patroni_cluster_master"

postgresql_hba_entries: "{{ _patroni_cluster_hba_base + _patroni_cluster_hba_extra }}"
postgresql_release: "{{ _patroni_cluster_release }}"
postgresql_initdb: false
postgresql_service_state: stopped
postgresql_service_masked: true
postgresql_service_enabled: false
postgresql_pip_manage: false
postgresql_locale: en_US.UTF-8
postgresql_conf_socketdir_manage: false
postgresql_nolog: "{{ _patroni_nolog }}"
