---
# Defaults
patroni_defaults_release_postgreql: '16.2'
patroni_defaults_release_patroni: '3.2.2'
patroni_defaults_release_consul: '1.18.1-1'

# Overridable values
_patroni_cluster_hostgroup: "{{ patroni_cluster_group | default('patroni_cluster') }}"
_patroni_barman_hostgroup: "{{ patroni_barman_group | default('patroni_barman') }}"
_patroni_update_skip_hostgroup: "{{ patroni_update_skip_group | default('patroni_update_skip') }}"
_patroni_consul_hostgroup: "{{ patroni_consul_group | default('patroni_consul') }}"
_patroni_haproxy_hostgroup: "{{ patroni_haproxy_group | default('patroni_haproxy') }}"

_patroni_release_postgresql: "{{ patroni_release_postgresql | default(patroni_defaults_release_postgreql) }}"
_patroni_release_patroni: "{{ patroni_release_postgresql | default(patroni_defaults_release_patroni) }}"
_patroni_release_consul: "{{ patroni_release_consul | default(patroni_defaults_release_consul) }}"

_patroni_config_hostnames: "{{ patroni_config_hostnames | default(True) }}"
_patroni_config_encoding: "{{ postgresql_locale | split('.') | last | regex_replace('-', '') }}"
_patroni_config_locale: "{{ postgresql_locale }}"

_patroni_watchdog_enable: "{{ patroni_watchdog_enable | default(True) }}"
_patroni_watchdog_mode: "{{ _patroni_watchdog_enable | bool | ternary('required', 'off') }}"

_patroni_cluster_release: "{{ _patroni_release_postgresql | split('.') | first }}"
_patroni_cluster_service_name: "{{ patroni_cluster_service_name | default('patroni') }}"
_patroni_cluster_name: "{{ patroni_cluster_name }}"
_patroni_cluster_api_username: "{{ patroni_cluster_api_username | default('patroni') }}"
_patroni_cluster_api_password: "{{ patroni_cluster_api_password }}"
_patroni_cluster_postgres_password: "{{ patroni_cluster_postgres_password }}"
_patroni_cluster_maxlag_failover: "{{ patroni_custer_maxlag_failover | default('1048576') }}"
_patroni_cluster_maxlag_sync: "{{ patroni_custer_maxlag_sync | default('-1') }}"
_patroni_cluster_replication_username: "{{ patroni_cluster_replication_username | default('replicator') }}"
_patroni_cluster_replication_password: "{{ patroni_cluster_replication_password }}"
_patroni_cluster_rewind_username: "{{ patroni_cluster_rewind_username | default('rewind') }}"
_patroni_cluster_rewind_password: "{{ patroni_cluster_rewind_password }}"
_patroni_cluster_backup_path: "{{ patroni_cluster_backup_path | default('/backups/patroni') }}"
_patroni_cluster_config_path: "{{ patroni_cluster_config_path | default('/etc/patroni') }}"
_patroni_cluster_config_file: "{{ _patroni_cluster_config_path }}/{{ (ansible_os_family == 'Debian') | ternary('config', 'patroni') }}.yml"
_patroni_cluster_start_timeout: "{{ patroni_cluster_start_timeout | default('60') }}"
_patroni_cluster_hba_extra: "{{ patroni_cluster_hba | default([]) }}"
_patroni_cluster_roles: "{{ patroni_cluster_roles | default([]) }}"
_patroni_cluster_databases: "{{ patroni_cluster_databases | default([]) }}"
_patroni_cluster_hba_base:
  - type: local
    database: all
    user: all
    auth_method: peer
  - type: host
    database: all
    user: all
    address: "127.0.0.1/32"
    auth_method: md5
  - type: host
    database: all
    user: all
    address: "::1/128"
    auth_method: md5
  - type: host
    database: all
    user: postgres
    address: "0.0.0.0/0"
    auth_method: reject
  - type: host
    database: all
    user: all
    address: "0.0.0.0/0"
    auth_method: md5
  - type: host
    database: replication
    user: "{{ _patroni_cluster_replication_username }}"
    address: "127.0.0.1/32"
    auth_method: md5
  - type: host
    database: replication
    user: "{{ _patroni_cluster_replication_username }}"
    address: "::1/128"
    auth_method: md5
  - type: host
    database: replication
    user: "{{ _patroni_cluster_replication_username }}"
    address: "0.0.0.0/0"
    auth_method: md5
  - type: host
    database: rewind
    user: "{{ _patroni_cluster_rewind_username }}"
    address: "127.0.0.1/32"
    auth_method: md5
  - type: host
    database: rewind
    user: "{{ _patroni_cluster_rewind_username }}"
    address: "::1/128"
    auth_method: md5
  - type: host
    database: rewind
    user: "{{ _patroni_cluster_rewind_username }}"
    address: "0.0.0.0/0"
    auth_method: md5

_patroni_consul_datacenter: "{{ patroni_consul_datacenter | default('patroni') }}"
_patroni_consul_backup_retention: "{{ patroni_consul_backup_retention | default('1440') }}"
_patroni_consul_backup_minutes: "{{ patroni_consul_backup_period | default('*/5') }}"
_patroni_consul_backup_hours: "{{ patroni_consul_backup_period | default('*') }}"
_patroni_consul_backup_days: "{{ patroni_consul_backup_period | default('*') }}"
_patroni_consul_backup_path: "{{ patroni_consul_backup_path | default('/backups/consul') }}"
_patroni_consul_backup_bin: "{{ patroni_consul_backup_bin | default('/usr/local/bin/consul-backup') }}"
_patroni_consul_restore_bin: "{{ patroni_consul_backup_bin | default('/usr/local/bin/consul-restore') }}"

_patroni_haproxy_config_file: "/etc/haproxy/haproxy.cfg"
_patroni_haproxy_user: "haproxy"
_patroni_haproxy_group: "haproxy"
_patroni_haproxy_maxconn: "{{ patroni_haproxy_maxconn | default(1000) }}"

# Hardcoded values
_patroni_groups_master: "_patroni_cluster_master"

postgresql_hba_entries: "{{ _patroni_cluster_hba_base + _patroni_cluster_hba_extra }}"
postgresql_release: "{{ _patroni_cluster_release }}"
postgresql_initdb: false
postgresql_service_state: stopped
postgresql_service_masked: true
postgresql_service_enabled: false
postgresql_pip_manage: false
postgresql_locale: en_US.UTF-8
postgresql_conf_socketdir_manage: false
