---
- name: Deploy Patroni extension - {{ _patroni_extension }}
  hosts: _patroni_cluster_master
  any_errors_fatal: true
  become: true
  vars_files:
    - main.yml
  tasks:
    - name: Set extension facts - {{ _patroni_extension }}
      ansible.builtin.set_fact:
        _extension_enable: "{{ lookup('ansible.builtin.vars', _extension_enable_vardef) }}"
        _extension_config: "{{ lookup('ansible.builtin.vars', _extension_config_vardef) }}"
        _extension_path: "{{ lookup('ansible.builtin.vars', _extension_path_vardef) }}"
      vars:
        _extension_enable_vardef: "{{ lookup('ansible.builtin.varnames', '^_patroni_cluster_' + _patroni_extension + '_enable$') }}"
        _extension_config_vardef: "{{ lookup('ansible.builtin.varnames', '^_patroni_cluster_' + _patroni_extension + '_config') }}"
        _extension_path_vardef: "{{ lookup('ansible.builtin.varnames', '^_patroni_config_' + _patroni_extension + '$') }}"

    - name: Unregister PostgreSQL extension - {{ _patroni_extension }}
      when: not (_extension_enable | bool)
      block:
        - name: Disable extension - {{ _patroni_extension }}
          community.postgresql.postgresql_query:
            query: "DROP EXTENSION IF EXISTS {{ _patroni_extension }}"
            db: postgres
          become_user: "{{ _postgresql_user }}"

        - name: Destroy PostgreSQL config - {{ _patroni_extension }}
          ansible.builtin.file:
            path: "{{ _postgresql_conf_include }}/{{ _extension_path }}"
            state: absent
          when: not (_extension_enable | bool)
          notify: postgresql_reload

    - name: Register PostgreSQL extension - {{ _patroni_extension }}
      when: _extension_enable | bool
      block:
        - name: Manage PostgreSQL include config - {{ _patroni_extension }}
          ansible.builtin.copy:
            dest: "{{ _postgresql_conf_include }}/{{ _extension_path }}"
            content: "{{ _extension_config }}"
            owner: "{{ _postgresql_user }}"
            group: "{{ _postgresql_group }}"
            mode: "u=rw,go=r"
          notify: patroni_reload

        - name: Enable extension - {{ _patroni_extension }}
          community.postgresql.postgresql_query:
            query: "CREATE EXTENSION IF NOT EXISTS {{ _patroni_extension }}"
            db: postgres
          become_user: "{{ _postgresql_user }}"

  handlers:
    - name: Reload Patroni
      ansible.builtin.service:
        name: "{{ _patroni_cluster_service_name }}"
        state: reloaded
      listen:
        - patroni_reload
        - postgresql_reload
      tags: always
