---
- name: Prepare stack nodes
  ansible.builtin.import_playbook: nephelaiio.patroni.prepare


- name: Deploy proxy nodes
  ansible.builtin.import_playbook: nephelaiio.patroni.haproxy


- name: Deploy Consul cluster
  ansible.builtin.import_playbook: nephelaiio.consul.install


- name: Deploy PostgreSQL cluster
  ansible.builtin.import_playbook: nephelaiio.patroni.patroni


- name: Deploy Barman nodes
  ansible.builtin.import_playbook: nephelaiio.patroni.barman


- name: Manage PostgreSQL databases
  ansible.builtin.import_playbook: nephelaiio.patroni.databases
