---
- name: Prepare nodes
  ansible.builtin.import_playbook: nephelaiio.patroni.prepare


- name: Deploy proxy nodes
  ansible.builtin.import_playbook: nephelaiio.patroni.haproxy


- name: Deploy Consul cluster
  ansible.builtin.import_playbook: nephelaiio.patroni.consul


- name: Deploy PostgreSQL cluster
  ansible.builtin.import_playbook: nephelaiio.patroni.patroni


- name: Deploy PostgreSQL cluster
  ansible.builtin.import_playbook: nephelaiio.patroni.barman
