---
- name: Set cluster facts
  ansible.builtin.import_playbook: nephelaiio.patroni.facts


- name: Deploy Patroni cluster members
  hosts: "{{ _patroni_cluster_hostgroup }}"
  become: true
  vars_files:
    - main.yml
  roles:
    - nephelaiio.patroni.pgdg
  tasks:
    - name: Check required parameters
      ansible.builtin.assert:
        that:
          - _patroni_cluster_name is defined
          - _patroni_cluster_api_password is defined
          - _patroni_cluster_replication_password is defined
          - _patroni_cluster_postgres_password is defined

    - name: Set PostgreSQL facts
      ansible.builtin.include_role:
        name: nephelaiio.patroni.postgresql
        tasks_from: vars.yml

    - name: Stat PostgreSQL config file
      ansible.builtin.stat:
        path: "{{ _postgresql_conf_main }}"
      register: _postgresql_conf_main_query

    - name: Deploy PostgreSQL packages
      ansible.builtin.include_role:
        name: nephelaiio.patroni.postgresql
      vars:
        postgresql_conf_main_file: "{{ _postgresql_conf_main_query.stat.exists | ternary('postgresql.base.conf', 'postgresql.conf') }}"

    - name: Install Patroni
      ansible.builtin.package:
        name:
          - patroni
          - python3-consul

    - name: Clean up configuration templates
      ansible.builtin.file:
        path: "{{ _patroni_cluster_config_path }}/{{ item }}"
        state: absent
      loop:
        - config.yml.in
        - dcs.yml

    - name: Manage cluster configuration
      ansible.builtin.template:
        src: "patroni.yml.j2"
        dest: "{{ _patroni_cluster_config_file }}"
        force: false
      vars:
        _slot: "[ '%s', { 'type': 'physical' } ]"
        _cluster_size: "{{ _cluster_hosts | length }}"
        _cluster_hosts: "{{ groups[_patroni_cluster_hostgroup] }}"
        _cluster_slots: "[ {{ _cluster_hosts | map('nephelaiio.plugins.map_format', _slot) | join(',') }} ]"
        _config_cluster_name: "{{ _patroni_cluster_name }}"
        _config_datadir: "{{ _postgresql_datadir }}"
        _config_socketdir: "{{ _postgresql_socketdir }}"
        _config_host_name: "{{ ansible_hostname }}"
        _config_configdir: "{{ _postgresql_confdir }}"
        _config_bindir: "{{ _postgresql_bindir }}"
        _config_address: "{{ ansible_default_ipv4.address }}:5432"
        _config_slots: "{{ _cluster_slots | community.general.dict | to_nice_yaml(indent=2) }}"
        _config_synchronous_node_count: "{{ _cluster_size | int - 2 }}"
        _config_api_username: "{{ _patroni_cluster_api_username }}"
        _config_api_password: "{{ _patroni_cluster_api_password }}"
        _config_replication_username: "{{ _patroni_cluster_replication_username }}"
        _config_replication_password: "{{ _patroni_cluster_replication_password }}"
        _config_postgres_password: "{{ _patroni_cluster_postgres_password }}"
        _config_watchdog_mode: "{{ _patroni_watchdog_mode }}"
        _config_encoding: "{{ _patroni_config_encoding }}"
        _config_locale: "{{ _patroni_config_locale }}"

    - name: Set cluster facts
      ansible.builtin.set_fact:
        _bootstrap_hostgroup: _patroni_cluster_bootstrap

    - name: Bootstrap Patroni cluster
      when: _bootstrap_hostgroup in groups
      block:
        - name: Start Patroni bootstrap service
          ansible.builtin.service:
            name: patroni
            state: started
            enabled: true

        - name: Wait for cluster initialization
          community.postgresql.postgresql_query:
            query: "SELECT pg_is_in_recovery()"
            db: postgres
          become: true
          become_user: "{{ _postgresql_user }}"
          register: _slave_query
          retries: 6
          delay: 10
          failed_when: _slave_query is failed or (_slave_query.query_result[0].pg_is_in_recovery | bool)

    - name: Set bootstrap facts
      ansible.builtin.set_fact:
        _groups_master: "_patroni_cluster_master"

    - name: Bootstrap Patroni cluster
      when: inventory_hostname in groups[_groups_master]
      block:
        - name: Start Patroni bootstrap service
          ansible.builtin.service:
            name: "{{ _patroni_cluster_service_name }}"
            state: started
            enabled: true

        - name: Start Patroni bootstrap service
          ansible.builtin.service:
            name: "{{ _patroni_cluster_service_name }}"
            state: started
            enabled: true

        - name: Wait for cluster startup
          community.postgresql.postgresql_info:
            filter:
              - version
          become: true
          become_user: "{{ _postgresql_user }}"
          retries: 18
          delay: 10
          register: _postgresql_version
          until: _postgresql_version is succeeded

    - name: Start Patroni slave services
      ansible.builtin.service:
        name: "{{ _patroni_cluster_service_name }}"
        state: started
        enabled: true

    - name: Manage PostgreSQL base config
      ansible.builtin.template:
        src: postgresql.conf.j2
        dest: "{{ _postgresql_confdir }}/postgresql.base.conf"
        owner: "{{ _postgresql_user }}"
        group: "{{ _postgresql_group }}"
        mode: 0644
      notify: patroni_reload

    - name: Manage Patroni profile
      ansible.builtin.lineinfile:
        path: "/etc/profile.d/patroni.sh"
        line: "alias patronictl='patronictl -c {{ _patroni_cluster_config_file }}'"
        create: true
        owner: root
        group: root
        mode: 0644

  handlers:
    - name: Reload Patroni
      ansible.builtin.service:
        name: "{{ _patroni_cluster_service_name }}"
        state: reloaded
      listen:
        - patroni_reload
        - postgresql_reload
