---
- name: Prepare Patroni stack members
  hosts: "{{ _patroni_cluster_hostgroup }}:{{ _patroni_barman_hostgroup }}:{{ _patroni_consul_hostgroup }}"
  become: true
  vars_files:
    - main.yml
  tasks:
    - name: Add host entries for cluster members
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: ".*{{ item }}.*"
        line: "{{ _member_address }} {{ _fqdn }} {{ _hostname }}"
      vars:
        _member_address: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
        _fqdn: "{{ hostvars[item]['ansible_fqdn'] }}"
        _hostname: "{{ hostvars[item]['ansible_hostname'] }}"
      loop: "{{ ansible_play_hosts }}"
      when: _patroni_config_hostnames

    - name: Install yum prerequisites
      ansible.builtin.package:
        name: python3-dnf-plugin-versionlock
      when: ansible_os_family == 'RedHat'


- name: Prepare Patroni Consul hosts
  hosts: "{{ _patroni_consul_hostgroup }}"
  become: true
  vars_files:
    - main.yml
  tasks:
    - name: Install cron for Debian derivatives
      ansible.builtin.package:
        name: cron
      when: ansible_os_family == "Debian"

    - name: Install cron for RedHat derivatives
      ansible.builtin.package:
        name: cronie
      when: ansible_os_family == "RedHat"


- name: Prepare Patroni PostgreSQL hosts
  hosts: "{{ _patroni_cluster_hostgroup }}"
  become: true
  vars_files:
    - main.yml
  tasks:
    - name: Configure watchdog support
      when: _patroni_watchdog_enable | bool
      block:
        - name: Load watchdog module
          community.general.modprobe:
            name: softdog
            persistent: present

        - name: Set watchdog permissions
          ansible.builtin.command: "chown {{ _postgresql_user }}:{{ _postresql_group }} /dev/watchdog"
