---
name: molecule

on:
  pull_request:
    branches:
      - master

jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - name: install
          - name: databases
          - name: barman
        image:
          - name: ubuntu2204
            command: /lib/systemd/systemd
          - name: debian12
            command: /lib/systemd/systemd
          - name: rockylinux9
            command: /usr/lib/systemd/systemd
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Update ubuntu repositories
        run: sudo apt-get update

      - name: Install make
        run: sudo apt-get install -y make

      - name: Install dependencies
        run: make install

      - name: Debug test environment
        run: make debug

      - name: Install role requirements
        run: make requirements

      - name: Run molecule tests.
        run: make test
        env:
          MOLECULE_DOCKER_IMAGE: ${{ matrix.image.name }}
          MOLECULE_DOCKER_COMMAND: ${{ matrix.image.command }}
          MOLECULE_SCENARIO: ${{ matrix.scenario.name }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
